#!/usr/bin/env bash
# ───────────────────────────────────────────────
# ZEUSAPOLLO GitHub Release Automation
# Usage: ./scripts/create_release.sh [--dry-run]
# Auto-detect latest version tag, generate changelog, create release
# ───────────────────────────────────────────────

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
GH_KEY="/root/.ssh/github_deploy"
GH_REPO="jamescashio/jamescashio.github.io"

# Colors
GREEN='\033[0;32m'
CYAN='\033[0;36m'
AMBER='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

dry_run=false
[[ "${1:-}" == "--dry-run" ]] && dry_run=true

echo -e "${CYAN}◆${NC} Detecting version from recent commits..."

cd "$REPO_DIR"

# Extract latest version from git log
LATEST_VERSION=$(git log --oneline -30 | grep -oP 'v\d+\.\d+[a-z]*(?:\.[a-z0-9]+)?' | head -1)
[[ -z "$LATEST_VERSION" ]] && LATEST_VERSION="v21.1"

# Find previous tag for changelog
PREV_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
if [[ -z "$PREV_TAG" ]]; then
  LOG_RANGE="HEAD"
  echo -e "${AMBER}⚠ No previous tag found — generating from all commits${NC}"
else
  LOG_RANGE="${PREV_TAG}..HEAD"
  echo -e "${GREEN}✓${NC} Previous tag: ${PREV_TAG}"
fi

echo -e "${CYAN}◆${NC} Version: ${LATEST_VERSION}"
echo -e "${CYAN}◆${NC} Building changelog..."

# Generate changelog
CHANGELOG=$(git log --oneline --no-decorate "$LOG_RANGE" 2>/dev/null | while read -r line; do
  commit_msg=$(echo "$line" | sed 's/^[a-f0-9]* //')
  echo "- $commit_msg"
done)

# Categorize commits
FEATURES=$(echo "$CHANGELOG" | grep -i "feat\|add\|new\|v[0-9]" || echo "")
FIXES=$(echo "$CHANGELOG" | grep -i "fix\|patch\|security\|xss\|bug\|sentinel" || echo "")
CHORES=$(echo "$CHANGELOG" | grep -vi "feat\|add\|new\|v[0-9]\|fix\|patch\|security\|xss\|bug\|sentinel\|status:" || echo "")

BODY=$(cat <<EOF
## ${LATEST_VERSION}

### ✨ Features
$(echo "$FEATURES" | head -10 | sed 's/^/- /')

### 🛡️ Fixes & Security
$(echo "$FIXES" | head -10 | sed 's/^/- /')

### 🔧 Chores
$(echo "$CHORES" | head -10 | sed 's/^/- /')

---

*Auto-generated by Hermes Agent • ${REPO_DIR##*/}*
EOF
)

echo -e "\n${GREEN}══════════════════════════════════${NC}"
echo -e "${CYAN}Release Preview:${NC}"
echo -e "${GREEN}══════════════════════════════════${NC}"
echo -e "Tag:    ${LATEST_VERSION}"
echo -e "Target: main"
echo -e "${BODY}"
echo -e "${GREEN}══════════════════════════════════${NC}\n"

if $dry_run; then
  echo -e "${AMBER}⚠ Dry run — not creating release${NC}"
  exit 0
fi

# Create tag
echo -e "${CYAN}◆${NC} Creating tag ${LATEST_VERSION}..."
git tag -a "$LATEST_VERSION" -m "Release ${LATEST_VERSION}"

echo -e "${CYAN}◆${NC} Pushing tag..."
GIT_SSH_COMMAND="ssh -i $GH_KEY -o StrictHostKeyChecking=no" git push origin "$LATEST_VERSION"

echo -e "${GREEN}✓${NC} Release ${LATEST_VERSION} created!"
echo -e "${CYAN}◆${NC} GitHub Release URL: https://github.com/${GH_REPO}/releases/tag/${LATEST_VERSION}"
